# Generated by Django 4.2.1 on 2023-06-08 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventsTb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_url', models.TextField(blank=True, null=True)),
                ('event_title', models.TextField(blank=True, null=True)),
                ('date_time', models.TextField(blank=True, null=True)),
                ('call_for_papers_date', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('topics', models.TextField(blank=True, null=True)),
                ('hash', models.TextField(blank=True, null=True)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorite_events', to='web_app.myappuser')),
            ],
            options={
                'db_table': 'events_tb',
            },
        ),
    ]
